### ISSUE TITLE
日历多选这里，如何限制它只能输入两个日期？

### ISSUE THREAD

**Issue by churjan** [wux-weapp/wux-weapp#108]
![qq 20181012091540](https://user-images.githubusercontent.com/15041918/46842271-54ed6a00-cdff-11e8-93c0-7254367ce506.png)

**Comment by churjan** [comment]
![image](https://user-images.githubusercontent.com/15041918/46842280-659de000-cdff-11e8-9067-7766d4282742.png)

**Comment by yuweizhang1991** [comment]
在回调里面自己判断
