### ISSUE TITLE
使用日历或者下拉框组件时，如果存在textarea组件后，层级显示会有问题

### ISSUE THREAD

**Issue by vanteking** [wux-weapp/wux-weapp#112]
[http://image09.hikedu.com/studystone/853930190/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20181015214336.png](url)

在表单里 textarea 在 日历的后面，当触发日历组件后，textarea的显示和组件使用都有问题，
手机型号: iphone 6s

**Comment by pollux611** [comment]
我也是这个问题，请问如何解决？
