### ISSUE TITLE
关于Cascader 级联选择器的数据源格式

### ISSUE THREAD

**Issue by Lingqinyu** [wux-weapp/wux-weapp#126]
https://wux-weapp.github.io/wux-weapp-docs/#/calendar
官方文档中级联选择器并没有给出JS的代码示例，也没有对数据源格式的说明，希望能详细补充完整

**Comment by Lingqinyu** [comment]
@skyvow 谢谢

**Comment by skyvow** [comment]
@Lingqinyu [cascader](https://wux-weapp.github.io/wux-weapp-docs/#/cascader)，后续会加入数据源格式的说明。
