### ISSUE TITLE
Cascader options数据源绑定bug

### ISSUE THREAD

**Issue by Lingqinyu** [wux-weapp/wux-weapp#130]
环境：
微信开发者工具v1.02.1809111
基础库2.3.2
（还未使用真机测试）

问题复现：
页面代码：
` <wux-cascader visible="{{ cascaderVisible }}" default-value="{{ cascaderValue }}" title="宿舍选择" options="{{ dormData }}" bind:close="onCascaderClose" bind:change="onCascaderChange" /> `
注：default-value属性值cascaderValue为空数组

**选择完“小区”之后，就会根据小区请求后台加载“宿舍”的数据，然后点击“宿舍”框，弹出Cascader选择器，如下图：**
![image](https://user-images.githubusercontent.com/20594036/47706958-7a82cc00-dc65-11e8-8bb8-a0e8a2b88d9d.png)

**此时Cascader的options数据是初始化写死的，见下图：**
![image](https://user-images.githubusercontent.com/20594036/47706215-a309c680-dc63-11e8-998e-7bc7d97bcbf2.png)
**点击一下“点击之前”这几个字，请求后台的数据才会显示，见下图：**
![image](https://user-images.githubusercontent.com/20594036/47706765-0a744600-dc65-11e8-9627-94b927659c12.png)
---------------------------------------------------------------------------------------------------------------

**如果不初始化options，也即是dormData[]，根本弹不出数据，无法进行操作，见下图：**
![image](https://user-images.githubusercontent.com/20594036/47706489-422ebe00-dc64-11e8-9a5d-692280f8f1d4.png)
-------------------------------------------------------------------------------------------------------------
数据绑定有延迟，应该是个bug。

**Comment by Lingqinyu** [comment]
@skyvow 还有一个场景也是同样的问题：选择小区1之后，点击加载出宿舍数据，然后取消“宿舍选择”操作后，重新选择小区2，然后再点击“宿舍”的时候，级联选择器弹出来的显示数据还是小区1的宿舍数据。
-------------------------------------------------------------------------------------------------------------------
哪里说得不清楚，欢迎及时提出，我会尽快补充

**Comment by skyvow** [comment]
@Lingqinyu 1.不初始化数据肯定无法操作。2.使用多个 cascader 选择器，不要用同一个去操作两个小区。

**Comment by 531431988** [comment]
动态获取的数据帮不上去？
