### ISSUE TITLE
希望可以完善npm引用的说明

### ISSUE THREAD

**Issue by RoyalOvesR** [wux-weapp/wux-weapp#131]
原生小程序开发，使用该文档的说明用起来很舒适，usingComponents复制粘贴就可以使用了。
现在由于种种原因，小程序采用了wepy框架进行开发，遇到了使用npm引入wux的难题，不知道这个框架中的usingComponents该怎么写。

**Comment by wxlacw** [comment]
希望大大能够讲讲wepy怎么使用该框架，举个栗子也好！！

**Comment by RoyalOvesR** [comment]
@wxlacw 我已经搞懂了该如何使用了，其实在src中某个文件夹引入wux-weapp文件夹即可，在wepy中config中使用usingComponents来引用想要的组件，wepy build --watch会自动把包拷贝进dist中
