### ISSUE TITLE
求解，关于Tabs标签页

### ISSUE THREAD

**Issue by OoNaruto** [wux-weapp/wux-weapp#132]
为何修改current属性，tabs不切换
![image](https://user-images.githubusercontent.com/21018675/47759647-82854f00-dceb-11e8-87ff-d724698b2f77.png)
![image](https://user-images.githubusercontent.com/21018675/47759650-8a44f380-dceb-11e8-9f23-eaee86702a61.png)

**Comment by skyvow** [comment]
仔细看示例

**Comment by OoNaruto** [comment]
> 仔细看示例
实例都看烂了老哥 求告知错误位置

**Comment by skyvow** [comment]
@OoNaruto 是不是最新版本呢？controlled 属性 v3.2.0 加入的。[changelog](https://wux-weapp.github.io/wux-weapp-docs/#/changelog)

**Comment by OoNaruto** [comment]
> @OoNaruto 是不是最新版本呢？controlled 属性 v3.2.0 加入的。[changelog](https://wux-weapp.github.io/wux-weapp-docs/#/changelog)
哎呀还真是 我上周三down的 。。没想到更新了！感谢大佬解答~
