### ISSUE TITLE
上传组件选择后就默认上传不符合一般业务逻辑！

### ISSUE THREAD

**Issue by hunshikan** [wux-weapp/wux-weapp#143]
上传组件用户选择完后，不应该直接就上传到后台，应该用户点击确定后再和后台交互。

**Comment by skyvow** [comment]
@hunshikan 仔细看文档，可以取消默认上传的。

**Comment by hunshikan** [comment]
我把文档看了个遍也没找到取消自动上传的参数！！！

**Comment by hunshikan** [comment]
默认的上传行为  是否禁用  是否监听上传进度变化  是否受控   我都试了每一个可以的
