### ISSUE TITLE
理论上所有表单组件都存在bug，无法和form标签一起配合使用，修改后才可以，折腾了一段时间才可用

### ISSUE THREAD

**Issue by zizhu8** [wux-weapp/wux-weapp#144]
以input组件为例：
1. 首先需要在input/index.js里面增加behaviors: ['wx://form-field'],这样保证在form表单提交的时候，可以提交name属性
2. 需要在properties属性里面增加name的属性，例如：
				name: {
					type: String,
					value: '',
				},
3. 最后需要修改一个updated函数，才能在提交表单的时候获取到值：
updated(inputValue) {
            if (this.data.inputValue !== inputValue) {
                this.setData({
//这里原来写错了，少了key
                    inputValue: inputValue
                })
            }
        },

作者确认下是否存在此问题，谢谢

**Comment by skyvow** [comment]
非 BUG，设计如此。

**Comment by mygoodidea** [comment]
请问使用该库，表单提交时有什么比较好的用法时间吗，不想为每个表单组件写一个change方法

**Comment by gudufy** [comment]
> 非 BUG，设计如此。

请问你是基于什么样的想法要这样设计呢？不能跟form一起工作，那这样的input有什么意义？

**Comment by tunghsingw** [comment]
from组件如何获取发送模板消息使用的formid
