### ISSUE TITLE
upload onbefore  fileList为空

### ISSUE THREAD

**Issue by DestinyHunter** [wux-weapp/wux-weapp#149]

**Comment by DestinyHunter** [comment]
返回file就对了.这样在before 能拿到file
![image](https://user-images.githubusercontent.com/20897838/48535461-64703f00-e8e6-11e8-8508-3cf84b0d491c.png)

**Comment by DestinyHunter** [comment]
受控的时候只能监听到onChange

**Comment by danwangwangdan** [comment]
@DestinyHunter 那onRemove监听是不是也要类似这样的调用一下才会删除文件？
