### ISSUE TITLE
没错，又是我，upload组件我感觉是有问题的

### ISSUE THREAD

**Issue by hunshikan** [wux-weapp/wux-weapp#152]
// 判断是否取消默认的上传行为
      if (uploaded) {
        this.uploadFile()
       }
从代码上看uploaded为true则为默认上传，我设置成false预览都看不到了，这样合理吗？

**Comment by heamon7** [comment]
@hunshikan 遇到一样的问题

**Comment by lansane** [comment]
我也遇到一样问题，怎么解决
