### ISSUE TITLE
filterbar type="radio" 下拉框显示不全是什么原因呢

### ISSUE THREAD

**Issue by roytime** [wux-weapp/wux-weapp#154]
items: [{
      type: 'radio',
      label: 'Status',
      value: 'updated',
      children: [{
        label: 'Example 1',
        value: 'desc',
      },
      {
        label: 'Example 2',
        value: 'asc',
      },
      ],
      groups: ['001'],
    }

当面后面还有别的代码。
我的意思是点击出现下拉菜单的情况的下，显示不全，前端只是显示一条数据，其他数据看不到，我知道其他数据有，但是都被遮住了。 有可能是什么情况呢？

这样描述，可能不直观。 但是，我不知道怎么上传图片

**Comment by FxPixels** [comment]
直接把图片拖到输入框就会自己上传了
