### ISSUE TITLE
提几个小建议

### ISSUE THREAD

**Issue by 531431988** [wux-weapp/wux-weapp#165]
比如card组件，body填充能否添加自定义padding值，有的时候不需要填充，很多组件都没有自定义class或style（比如card的标题太大了，我想修改一下不支持，不也支持slot=title，无奈很多组件都只能自己复制一份在修改），比如divider组件能否支持定义margin

还有其他的就不一一列举了，非常的不灵活，比如button没必要那么多颜色吧（parimary info success error warning应该够了吧，在给个color自定义，或者给个class自定义，也不支持圆角圆形按钮）

**Comment by skyvow** [comment]
@531431988 可以提 PR
