### ISSUE TITLE
画廊组件加载大图片列表时自动退出（仅iphone）

### ISSUE THREAD

**Issue by jerry79** [wux-weapp/wux-weapp#169]
在加载大量图片列表时，使用画廊组件，查看了超过60张大图后，小程序就自动退出了。
仅在Iphone端如此，安卓没问题。
我查了很多资料，都说是微信小程序本身以及Iphone的问题，但是这个组件还有办法优化吗？能够避免再加载大量图片列表后的问题吗？
谢谢了。

**Comment by FxPixels** [comment]
或许是需要这个` IntersectionObserver`

**Comment by skyvow** [comment]
@jerry79 暂时没好的解决方案
