### ISSUE TITLE
反馈一个bug

### ISSUE THREAD

**Issue by Vlong123** [wux-weapp/wux-weapp#170]
动画组选择slideInRight时，页面整体都可以移动到右边去，超出页面范围了

**Comment by skyvow** [comment]
@Vlong123 描述可能不直观，可否提供图片参考

**Comment by Vlong123** [comment]
![67ba228e537ae3f7bc345cb8efe63098](https://user-images.githubusercontent.com/35003262/50382144-8a51e600-06d3-11e9-9908-9a1dc7ec225f.png)
看这张图，选了slideInRight，手向左滑动，页面整体偏移了
