### ISSUE TITLE
求新增个能一同选择日期跟时间的组件

### ISSUE THREAD

**Issue by djjx5227** [wux-weapp/wux-weapp#172]
现在的Calendar组件只能选择日期，如果还有时间要选择的话就又得另外点开一个其他组件。所以能否把时间的选择跟日期的选择放在一起？坐等更新~~谢谢^_^

**Comment by skyvow** [comment]
@djjx5227 欢迎提 PR

**Comment by skyvow** [comment]
v3.7.0+ 已支持 DatePicker 组件
