### ISSUE TITLE
wux-accordion-group  current设置后没有效果

### ISSUE THREAD

**Issue by Victor2LYX** [wux-weapp/wux-weapp#181]
按照官方教程设置，current改变页面是不重新渲染的，按照下面方法修改后，current改变页面会重新渲染。

<wux-accordion-group  controlled current="{{accordionCurrent}}">
改为  <wux-accordion-group  auto='{{false}}' current="{{accordionCurrent}}">   
另外需要在组件accordion-group/index.js 里面屏蔽if判断
   methods: {
        updated(activeKey, condition) {
            const elements = this.getRelationNodes('../accordion/index')

            if (elements.length > 0) {
                // if (condition) {
                    this.setData({
                        activeKey,
                    })

                    elements.forEach((element, index) => {
                        const key = element.data.key || String(index)
                        const current = this.data.accordion ? activeKey[0] === key : activeKey.indexOf(key) !== -1

                        element.changeCurrent(current, key)
                    })
                // }
            }

            if (this.data.keys.length !== elements.length) {
                this.setData({
                    keys: elements.map((element) => element.data)
                })
            }
        },

**Comment by skyvow** [comment]
@Victor2LYX use controlled

**Comment by Victor2LYX** [comment]
> @Victor2LYX use controlled

你好，如果使用controlled，点击组件右侧折叠/展开按钮，会触发accordion-group/index.js文件里面setActiveKey，然后触发this.updated(activeKey, !this.data.controlled),此时updated方法第二个入参为false，不会触发accordion组件changeCurrent方法。也就无法展开/折叠了。最简单的方法是屏蔽if (condition)判断，但是会加大渲染开销。

**Comment by Victor2LYX** [comment]
@skyvow  你好，如果使用controlled，点击组件右侧折叠/展开按钮，会触发accordion-group/index.js文件里面setActiveKey，然后触发this.updated(activeKey, !this.data.controlled),此时updated方法第二个入参为false，不会触发accordion组件changeCurrent方法。也就无法展开/折叠了。最简单的方法是屏蔽if (condition)判断，但是会加大渲染开销。

**Comment by skyvow** [comment]
@Victor2LYX 请仔细看文档及示例

**Comment by Victor2LYX** [comment]
@Victor2LYX 非常感谢！

**Comment by Victor2LYX** [comment]
@skyvow 非常感谢
