### ISSUE TITLE
关于Cascader级联选择组件

### ISSUE THREAD

**Issue by mahaoming** [wux-weapp/wux-weapp#187]
![_20190109092055](https://user-images.githubusercontent.com/31064550/50869686-08123300-13f0-11e9-84a2-2b10647ddf09.png)
你好，请问Cascader级联选择组件，会出现要点击两次才出现二级的情况，是为什么呢

**Comment by JiYingJun** [comment]
同样在mpvue中出现相同问题，他应该是在date里声明title:' '，这样导致onchange之后title的值已经锁定了，请作者看看在mpvue里要怎么解决这个问题
