### ISSUE TITLE
新版本3.4.0~3.5.0的cell-group出现bug：全局multipleSlots导致异常表现

### ISSUE THREAD

**Issue by shui0855** [wux-weapp/wux-weapp#188]
在使用cell-group中，放置多个cell，其中首先的cell些是<block wx:for="...">生成的，后面的cell则是直接写入的，在页面展示的时候经常会出现顺序错乱的情形，<block wx:for="...">生成的cell总是被放置到直接写入的cell的后面，而且两部分间的分割横线(——)还消失了。经过检查，发现因为使用了组件全局设置("../helpers/baseComponent.js")，其中multipleSlots=true，导致小程序在slot解析的时候会把组件中的多个子组件(cell)解析为多个slot而不是共用一个slot(这里也许是小程序框架的一个bug)。组件cell-group的multipleSlots设为false之后，显示恢复正常，按wxml的编排顺序显示。所以cell-group的multipleSlots不该设置为true。
至于其它组件有没有类似的问题，不适合使用全局设定的，还请作者大大多检查下。

**Comment by skyvow** [comment]
@shui0855 可否提供一个简单示例呢

**Comment by shui0855** [comment]
> @shui0855 可否提供一个简单示例呢
例子:
`<wux-cell-group>
  <block wx:for="{{['A','B','C']}}">
    <wux-cell title="{{item}}" />
  </block>
  <wux-cell title="T" />
</wux-cell-group>`
例中T应该显示在ABC的下边，但在3.4.0的wux中实际显示却是T在ABC的上边，在3.3.2则正常，差异在于multipleSlots

**Comment by skyvow** [comment]
@shui0855 经测试开发者工具与真机上都显示正常，T 在 ABC 的下边。

**Comment by shui0855** [comment]
> @shui0855 经测试开发者工具与真机上都显示正常，T 在 ABC 的下边。

例中`block wx:for`的`['A','B','C']`是静态，而我实际的代码中是动态通过page.setData()更新的数组，而且将multipleSlots改成false则回复正常了

**Comment by shui0855** [comment]
已经更新到3.5.0，这个bug还是没给解决啊，我特意写了个重现的page代码并做了截图(见附件)，还是请给仔细检查检查吧，就是个改默认参数multipleSlots就能解决的问题。
js:
`Page({
  data: {},
  onLoad() { this.list() },
  list(e) {
    let { list } = this.data
    list = (list && list.length > 0) ? [] : [...Array(5)].map((v, i) => i + 1)
    this.setData({ list })
  },
})`
wxml:
`<view class="page">
  <view class="page__bd page__bd_spacing">
    <view class="sub-title">按钮</view>
    <wux-button block type="balanced" catch:click="list">list {{list&&list.length>0?'Clear':'Fill'}}</wux-button>
  </view>
  <view class="page__bd">
    <wux-cell-group title="友人" wx:if="{{true}}">
      <block wx:for="{{list}}" wx:key="">
        <wux-cell title="标题[{{index}}]" label="内容[{{index}}]" extra="结尾[{{index}}]" is-link />
      </block>
      <wux-cell title="标题" label="内容" extra="结尾" is-link />
      <wux-cell title="禁用" disabled />
    </wux-cell-group>
  </view>
</view>`
json:
`{
  "navigationBarTitleText": "Button",
  "usingComponents": {
    "wux-button": "../../dist/button/index",
    "wux-cell-group": "../../dist/cell-group/index",
    "wux-cell": "../../dist/cell/index"
  }
}`
附件：
![b](https://user-images.githubusercontent.com/9348021/53229802-29895e80-36c0-11e9-8af1-1b7d2fc2e4d8.png)
