### ISSUE TITLE
Rating component在真机上错位，模拟器中正常。

### ISSUE THREAD

**Issue by xtheo** [wux-weapp/wux-weapp#19]
![20170916154023](https://user-images.githubusercontent.com/9459712/30510431-63515652-9af6-11e7-98b4-2f05633c54f2.jpg)

Rating component在真机上错位，模拟器中正常。

**Comment by skyvow** [comment]
@xtheo 什么机型？可能是样式问题导致的。

**Comment by xtheo** [comment]
@skyvow 手头测试过一加三 和 苹果6，均错位。

**Comment by AlonsoZeng** [comment]
我也遇到这个问题，求解

**Comment by skyvow** [comment]
@xtheo @AlonsoZeng iphone6\6s\6p\vivo x6 p都测试了没有发现问题，有没有可能是微信版本影响？

**Comment by yuhongde** [comment]
我用mac开发工具预览是好的，用windows开发工具预览就坏了
