### ISSUE TITLE
长页面用力滑动时会触发下拉刷新

### ISSUE THREAD

**Issue by XtLee** [wux-weapp/wux-weapp#190]
长页面用力滑动时，如果触顶就会触发刷新。能否判断一下用户是手动下拉还是滑动页面？？

![image](https://user-images.githubusercontent.com/30145777/51020937-021c7d80-15bb-11e9-870c-f8ab6d01a1e1.png)
![image](https://i.loli.net/2019/01/11/5c384f7b08e0b.jpg)

**Comment by skyvow** [comment]
@XtLee 有点不好区分

**Comment by FxPixels** [comment]
> @XtLee 有点不好区分

可以考虑用scrollTop判断…
