### ISSUE TITLE
Cascader 级联选择器组件default-value无效

### ISSUE THREAD

**Issue by PaytonCheung** [wux-weapp/wux-weapp#195]
看example中 `default-value="{{ value1 }}"`但是在js中并没有使用或者设置该变量. 文档上说就是一个数组, 但是数组里面是什么也没有说明, 尝试几种设置value1的值都无法做到一打开就默认选中城市的效果. 请问是什么问题??

**Comment by miawang96** [comment]
> @PaytonCheung 没有问题啊

我碰到了一样的问题。。

**Comment by yoage** [comment]
@skyvow  文档里面是否有个例子，告诉我们默认value1 数组数据格式

**Comment by yoage** [comment]
` value1: [
      "110000",
      "110100"
    ]`

value是这样的数据结构，测试有效
