### ISSUE TITLE
3.4.0+ wux-filterbar 在 mpvue 下初始化数据时 items 为空

### ISSUE THREAD

**Issue by imyellow** [wux-weapp/wux-weapp#200]
![image](https://user-images.githubusercontent.com/3270774/51656478-43118a80-1fdc-11e9-8390-1b5d8b78fd0c.png)

dist/filterbar/index.js 最后几行的位置，因为 mpvue 的 data 在小程序 created 之后才会赋值，所以导致这个时候取到的 items 是个空数组，加个 timeout 解决。

![image](https://user-images.githubusercontent.com/3270774/51656513-62a8b300-1fdc-11e9-8ba1-b408c08ed731.png)

**Comment by jyhs** [comment]
还是不行啊 依旧不显示filter
template：
              <wux-filterbar :items="items" @change="onChange" @open="onOpen" @close="onClose" />

js：
 mounted () {
    setTimeout(() => {
      this.items = [{
        type: 'radio',
        label: 'Updated',
        value: 'updated',
。。。。

**Comment by imyellow** [comment]
> 还是不行啊 依旧不显示filter
> template：
> <wux-filterbar :items="items" @change="onChange" @OPEN="onOpen" @close="onClose" />
> 
> js：
> mounted () {
> setTimeout(() => {
> this.items = [{
> type: 'radio',
> label: 'Updated',
> value: 'updated',
> 。。。。

在 /filterbar/index.js 最后那里加
