### ISSUE TITLE
select组件增加自动定位到已选择项功能更好一点

### ISSUE THREAD

**Issue by nullNoneStack** [wux-weapp/wux-weapp#203]
当用户不传递定位索引，自动定位到已选中的第一个，用户传递了定位索引，则定位到用户传递的地方。
随意改动了一下，实现了这个功能，可能改的不好，希望改进一下。
下面是一些改动记录：
![image](https://user-images.githubusercontent.com/41111428/51721522-3862fe00-208d-11e9-9523-04c89e7b0990.png)

![image](https://user-images.githubusercontent.com/41111428/51721517-297c4b80-208d-11e9-88e1-5bf8bb5fd692.png)

![image](https://user-images.githubusercontent.com/41111428/51721739-fd14ff00-208d-11e9-87c5-2d872ac2f3e9.png)

**Comment by skyvow** [comment]
v3.5.0 已加入支持。
