### ISSUE TITLE
微信开发者工具显示组件

### ISSUE THREAD

**Issue by miawang96** [wux-weapp/wux-weapp#206]
Hi, 最近开发mpvue项目使用了Cascader和Calendar两个组件，发现在微信开发者工具（v1.02.1812271）上的显示异常，但是在真机上基本没问题，请问这是什么原因呢？

**Comment by skyvow** [comment]
@miawang96 截个图

**Comment by miawang96** [comment]
![image](https://user-images.githubusercontent.com/38304003/52547130-1cd35380-2e00-11e9-86fd-eb171d4a76f0.png)

**Comment by miawang96** [comment]
> @miawang96 截个图

![image](https://user-images.githubusercontent.com/38304003/52547134-2bba0600-2e00-11e9-92ce-ba0b170ce36d.png)

**Comment by skyvow** [comment]
https://wux-weapp.github.io/wux-weapp-docs

**Comment by miawang96** [comment]
> https://wux-weapp.github.io/wux-weapp-docs

原来是我文档没看仔细吗？

**Comment by miawang96** [comment]
> > https://wux-weapp.github.io/wux-weapp-docs
> 
> 原来是我文档没看仔细吗？

谢谢，是自己小程序基础库版本太低了
