### ISSUE TITLE
小程序中使用Cascader级联选择器的chooseTitle不显示

### ISSUE THREAD

**Issue by bobosbenben** [wux-weapp/wux-weapp#207]
当数据格式为以下情况时：
`[{
    'label': '北京',
    'value': '110000',
    'children': [{
        'label': '北京市',
        'value': '110000',
        'children': [{
            'label': '东城区',
            'value': '110101',
        }],
    }],
}, {
    'label': '上海',
    'value': '310000',
    'children': [{
        'label': '上海市',
        'value': '310000',
        'children': [{
            'label': '黄浦区',
            'value': '310101',
        }]
    }],
}]`
会出现如下的效果：
![default](https://user-images.githubusercontent.com/12725799/52609040-e3a9ea80-2eb6-11e9-8f6d-4be81eca14b2.png)

但是，当我的数据格式如下的时候：
`[{
      'label': '北京',
      'value': '110000',
      'children': [{
        'label': '北京市',
        'value': '110100',
        'children': [{
          'label': '东城区',
          'value': '110101',
        }, {
            'label': '西城区',
            'value': '110102',
          }],
      }],
    }, {
      'label': '上海',
      'value': '310000',
      'children': [{
        'label': '上海市',
        'value': '310000',
        'children': [{
          'label': '黄浦区',
          'value': '310101',
        }]
      }],
      }, { "label": "内蒙古", "value": "2", "children": [{ "label": "鄂尔多斯", "value": "3", "children": null }, { "label": "包头", "value": "10", "children": null }] }]`
会出现如下效果：

所以我的猜测是：当第一层级的个数为2的时候，chooseTitle只会出现2次，即数据里有北京、上海时，“请选择”只出现了2次，选择第三层级的“区”的时候没有出现“请选择”；当第一层级的个数为3或大于3的时候，chooseTitle会出现3次，即数据里有北京、上海、内蒙古时，“请选择”出现了3次，选择第三层级的“区”的时候出现了“请选择”。

**Comment by bobosbenben** [comment]
![default](https://user-images.githubusercontent.com/12725799/52609302-c3c6f680-2eb7-11e9-94f9-b137d7aa9c0c.png)

**Comment by yoage** [comment]
我也遇到同样的问题
