### ISSUE TITLE
filterbar 可以从后端获取filter选项吗

### ISSUE THREAD

**Issue by Sawyer-zh** [wux-weapp/wux-weapp#208]
之前使用的filterbar , 选项没几个写死了  现在选项多了  从后端获取之后 setData 发现不起作用

**Comment by skyvow** [comment]
@Sawyer-zh 目前不支持。

**Comment by Sawyer-zh** [comment]
@skyvow 不知道如何先拉取数据  打印看了下  页面执行onload之前 组件就已经渲染完成了

**Comment by QvQQ** [comment]
可以根据wux的代码，稍做修改，实现每次点击时从后端实时拉取分类以及子分类的功能。

**Comment by canyu9512** [comment]
我在items那边添加了一个监听，items变化就更新options，可以得到外面的items变化时更新组件，就是不知道会不会有什么其他问题

**Comment by LgdMagic** [comment]
> 我在items那边添加了一个监听，items变化就更新options，可以得到外面的items变化时更新组件，就是不知道会不会有什么其他问题

如何实现呢？

**Comment by misakichan** [comment]
data里初始化一个值（别为空），然后在页面显示后再去请求数据并渲染就可以了，在create或onload方法里不行

**Comment by duanzhichao** [comment]
后断获取的话,排序有问题,不能使用

**Comment by misakichan** [comment]
> 后断获取的话,排序有问题,不能使用

需要修改插件源码，miniprogram/miniprogram_npm/wux-weapp/filterbar/index.wxml文件下的所有wx:key配置一下就行，源码里默认是空。
