### ISSUE TITLE
左滑事件和点击事件冲突

### ISSUE THREAD

**Issue by mencomao** [wux-weapp/wux-weapp#209]
在列表中使用左滑删除功能，无法再点击该cell进入详情，怎么解决，谢谢

**Comment by yandixuan** [comment]
我在mpvue嵌套组件，组件click事件失效。去除wux-swipe-action事件可以触发
@skyvow

**Comment by smartymoon** [comment]
遇到同样问题，没用 mpvue ，原生开发。当 tap 定义在 wux-swipe-action 中就不会触发

**Comment by pengweiqiang** [comment]
> 在列表中使用左滑删除功能，无法再点击该cell进入详情，怎么解决，谢谢
你好，你的怎么解决了？

**Comment by yandixuan** [comment]
> > 在列表中使用左滑删除功能，无法再点击该cell进入详情，怎么解决，谢谢
> > 你好，你的怎么解决了？

![image](https://user-images.githubusercontent.com/23276822/53322600-ce9d7480-3916-11e9-9cae-87bb73d34376.png)
源码这里用的是catch 捕获了点击事件

**Comment by DaiHuaXieHuaKai** [comment]
将组件中的content部分中catchtouchstart改成bindtouchstart就可以了

**Comment by Ewall1106** [comment]
> 将组件中的content部分中catchtouchstart改成bindtouchstart就可以了

改了也没效果？？
