### ISSUE TITLE
求强化日期组件功能，支持弹窗或者滚动条

### ISSUE THREAD

**Issue by Pointerv** [wux-weapp/wux-weapp#218]
您好，用了很长时间wux，感觉很方便很好用。谢谢提供了这么好用的组件。在使用过程中，也收到一些类似以下截图的需求。不知道有没有计划实现一下？
![screenshot_20190227_165624](https://user-images.githubusercontent.com/11025512/53478374-99795980-3ab1-11e9-8c63-f0da24b0d1da.jpg)
![screenshot_20190227_163910_cn xuexi android](https://user-images.githubusercontent.com/11025512/53478375-99795980-3ab1-11e9-947e-fa2a3dc82022.jpg)
![screenshot_20190227_163904_cn xuexi android](https://user-images.githubusercontent.com/11025512/53478376-9a11f000-3ab1-11e9-8818-690868a40cf3.jpg)

**Comment by skyvow** [comment]
@Pointerv 可以使用 DatePicker 组件
