### ISSUE TITLE
Refresher下拉刷新来回滚动卡顿回滚后不应刷新

### ISSUE THREAD

**Issue by Honye** [wux-weapp/wux-weapp#22]
上下来回滚动的时候有卡顿现象；
下拉再回滚到初始位置时应不刷新。
![wux-refresher](https://user-images.githubusercontent.com/19296374/31978395-cb307fdc-b973-11e7-8e8d-70c837c5b257.gif)

**Comment by cloverstd** [comment]
在 Mac 上没有复现

请提供一下操作系统版本、开发者工具的版本

**Comment by Hongye567** [comment]
没有 Mac ；操作系统：Win10；开发工具版本：v1.01.171019

**Comment by Hongye567** [comment]
这个问题主要出现在Android上，适配没做好。
我iOS手机运行完全没问题，在Android ( 红米2A ) 上就无法适配，还卡顿

**Comment by missDEzhou** [comment]
大大，这个问题解决了嘛？
