### ISSUE TITLE
index-list 异步获取数据源 字母滑动失效

### ISSUE THREAD

**Issue by createskyak** [wux-weapp/wux-weapp#224]
如题，在异步返回的函数中赋值，字母列表出，只能点击，不能滑动了
![image](https://user-images.githubusercontent.com/24787348/54064621-f7940280-4250-11e9-9b89-8e783e5dbdbc.png)
![image](https://user-images.githubusercontent.com/24787348/54064630-1a261b80-4251-11e9-80da-67ff932e1e07.png)

**Comment by chobits4** [comment]
遇到了相同问题

**Comment by xieweijv** [comment]
同样的问题

**Comment by QYZX** [comment]
dist/index/index.js
这个方法执行后rects获取的数量有误
`   /**
         * 获取右侧导航对应的坐标
         */
        getNavPoints() {
            const className = `.${this.data.prefixCls}__nav-item`
            wx
                .createSelectorQuery()
                .in(this)
                .selectAll(className)
                .boundingClientRect((rects) => {
                    if (rects.filter((n) => !n).length) return
                    this.setData({
                        points: rects.map((n) => ({ ...n, offsets: [n.top, n.top + n.height] })),
                    })
                })
                .exec()
        },`

目前我在onTouchStart方法中再次调用一次getNavPoints方法可以解决
`  /**
         * 手指触摸动作开始
         */
        onTouchStart(e) {
            this.getNavPoints()
            if (this.data.moving) return
            const { index, name } = e.target.dataset
            this.setActive(index, name)
            this.setData({ moving: true })
        },`

**Comment by xieweijv** [comment]
我项目里的这个问题已经解决了，原因是设置高度设置成100%了，应该设置具体的数值，比如100vh。
如果设置成100%，wux-index里面使用的scroll-view的scroll-top就会失效，所以要设置成具体的高度，具体参考微信官方关于scroll-view的文档。
