### ISSUE TITLE
有关ActionSheet和Circle一起共用时的Z轴高度问题

### ISSUE THREAD

**Issue by a28293971** [wux-weapp/wux-weapp#233]
如图所示

![1505B759AB2E522D7CBE5B3FD56ADB0B](https://user-images.githubusercontent.com/28895420/55244967-26fcc480-527d-11e9-866a-bdc23d8116eb.png)

当使用ActionSheet时，如果出现和Circle组件重叠的地方(重叠的部分是组件内的canvas吧)
就会出现其后者覆盖在前者上的情况，我希望可以把菜单的z轴提高。
但是根据目前的ActionSheet文档描述可以使用自定义的类。不过还是使用一个自定义的style把其
`style='z-index:9999;'`
比较方便对吧。如果把这项样式单写到一个类里当成参数赋值过去可能会直接覆盖掉原本的全部样式。这就越来越取得反效果了。
不知道有没有人和我遇到过相同的情况，并且有不错的解决办法。
谢谢大家了。

**Comment by skyvow** [comment]
@a28293971 [原生组件](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)

**Comment by a28293971** [comment]
试了好多小程序官方说的“cover-view”或着“cover-image“ 都没有达到想要的效果
