### ISSUE TITLE
项目集成style无法生效

### ISSUE THREAD

**Issue by ddwhan0123** [wux-weapp/wux-weapp#252]
￼运行效果如下
![1557905288387](https://user-images.githubusercontent.com/9019351/57756607-339e8480-7726-11e9-9f01-c88149ed0bb9.jpg)

调用端 index.json
<img width="436" alt="屏幕快照 2019-05-15 下午3 32 14" src="https://user-images.githubusercontent.com/9019351/57756815-a27bdd80-7726-11e9-97c3-cfcc43921174.png">
调用端 index.wxml
<img width="697" alt="屏幕快照 2019-05-15 下午3 32 32" src="https://user-images.githubusercontent.com/9019351/57756839-ad367280-7726-11e9-9ba7-91ca39f3ac9c.png">
入口app.wxss
`@import 'assets/styles/weui.wxss';
@import 'assets/styles/skyvow.wxss';`

**Comment by ddwhan0123** [comment]
所有样式内容不生效 按照readme的说明 .dist文件完全copy 包括内部的 helpers

**Comment by ddwhan0123** [comment]
这是wxml的截图
<img width="759" alt="屏幕快照 2019-05-15 下午3 58 55" src="https://user-images.githubusercontent.com/9019351/57758492-62b6f500-772a-11e9-8689-2ae62c8d8d83.png">

**Comment by Gentear** [comment]
![image](https://user-images.githubusercontent.com/14846974/57911110-747ad280-78b9-11e9-8153-cd24ad7e239d.png)

希望能帮到你

**Comment by ddwhan0123** [comment]
谢谢 我 换个版本看下 @Gentear
