### ISSUE TITLE
使用notice-bar组件无法滚动到最后

### ISSUE THREAD

**Issue by ownsit** [wux-weapp/wux-weapp#255]
notice-bar组件内的文本如果太长超出屏幕可视区域，文本的滚动是无法到达文本末端的，只会滚动到文本的可视末端。
原因：在ready 周期里调用initAnimation方法时元素宽度的获取没有等到元素创建完成，内容此时还未正常添加到view中
解决方案：
我打开组件源码，将调用组件的init方法注释掉，给notice-bar添加一个id，在当前页面的生命周期中调用initAnimation方法
Page:
<notice-bar id="notice">
onload(){
let notice = this.selectComponent('#notice');
notice.initAnimation();
}

**Comment by skyvow** [comment]
@ownsit fixed
