### ISSUE TITLE
wux select  对 透明,手机上不能遮盖 textarea文字

### ISSUE THREAD

**Issue by 867511789** [wux-weapp/wux-weapp#258]
wux select 下拉框透明

**Comment by 867511789** [comment]
wux select 下拉框能看不下面的字。效果很不好 ，弄成不透明了，右边的选择又出来

**Comment by 867511789** [comment]
<wux-input label="企业名称" value="{{ qiyeInfo.name }}" controlled bind:change="onBlurName" />
</wux-cell> 更新了下  input  value不显示了

**Comment by skyvow** [comment]
@867511789 原生层级最高

**Comment by 867511789** [comment]
我知道 但不好解决。 不想象别的情况，wx-if 弄没了也不合适。只能自己做个窗体做单选
