### ISSUE TITLE
npm安装3.6.0+ 找不到版本的问题

### ISSUE THREAD

**Issue by ja5364** [wux-weapp/wux-weapp#265]
npm install wux-weapp@3.6.0
npm install wux-weapp@3.6.1
通过npm和cnpm安装都失败了
[wux-weapp@3.6.1] Can't find package wux-weapp's version: 3.6.1

**Comment by ihamy** [comment]
@ja5364 用的淘宝npm源吧？更换下，还原为官方的即可。淘宝没同步。
