### ISSUE TITLE
stikcy中的数据做分页加载后，往下滚动后就不吸顶了？

### ISSUE THREAD

**Issue by jechtliu** [wux-weapp/wux-weapp#269]
![image](https://user-images.githubusercontent.com/5267994/60418239-0560ff80-9c15-11e9-9895-f34954aa7f21.png)
第一页的时候可以吸顶，
![image](https://user-images.githubusercontent.com/5267994/60418289-2295ce00-9c15-11e9-9f5c-8440b210f395.png)
第二页的时候就不行了
![image](https://user-images.githubusercontent.com/5267994/60418319-35100780-9c15-11e9-8de2-57313a5ec368.png)
上面是js

**Comment by skyvow** [comment]
@jechtliu 可能高度未重新计算导致的，试试分页时调用 this.selectComponent(selector).updated() 更新高度

**Comment by LgdMagic** [comment]
> @jechtliu 可能高度未重新计算导致的，试试分页时调用 this.selectComponent(selector).updated() 更新高度
在哪里调用
