### ISSUE TITLE
Babelrc not correct

### ISSUE THREAD

**Issue by sky-admin** [wux-weapp/wux-weapp#272]
你代码中使用了 扩展运算符（...），Babelrc里应该包含stage-2。

https://github.com/didi/mpx/issues/124

(btw: 贵项目用的[gulp3.x和node12不兼容](https://github.com/gulpjs/gulp/issues/2324)了已经，有没有可能考虑改用mpx框架来维护该套组件库呢？mpx框架是基于webpack的，如有进一步了解的意向，我们可以微信聊聊)

**Comment by skyvow** [comment]
@sky-admin 感谢反馈呀，看了下决定升级到 gulp4.x。
