### ISSUE TITLE
存在将未绑定在 WXML 的变量传入 setData 

### ISSUE THREAD

**Issue by superlbr** [wux-weapp/wux-weapp#275]
变量名 | 调用堆栈 | 调用组件 | 页面
-- | -- | -- | --
bordered |   | static/wux/grid/index | pages/index/main
disabledMin |   | static/wux/input-number/index | pages/cart/main
disabledMax |   | static/wux/input-number/index | pages/cart/main

**Comment by skyvow** [comment]
哦
