### ISSUE TITLE
wux-date-picker 在 wux-form内有默认值，打开picker后直接确定，值被篡改了

### ISSUE THREAD

**Issue by GitOfZGT** [wux-weapp/wux-weapp#277]
wux-date-picker在表单中有一个默认值，打开picker后在不修改任意值的情况下点确定，默认值被篡改了  
官方demo里：
![image](https://user-images.githubusercontent.com/21262000/61272747-67eff900-a7da-11e9-9933-f603f2c6f9db.png)  

![image](https://user-images.githubusercontent.com/21262000/61272686-468f0d00-a7da-11e9-8c94-381cb95f1737.png)  

![image](https://user-images.githubusercontent.com/21262000/61272848-ad142b00-a7da-11e9-89cb-b104138a80dc.png)

![image](https://user-images.githubusercontent.com/21262000/61272891-c1582800-a7da-11e9-8760-3803c6c57753.png)

**Comment by skyvow** [comment]
@GitOfZGT 感谢反馈，由于日期组件内部用的是字符串比较，所以建议外部传入字符串 ['2019', '2', '1', '0', '0']。
