### ISSUE TITLE
企业微信小程序提示基础库版本低

### ISSUE THREAD

**Issue by thlz998** [wux-weapp/wux-weapp#284]
微信小程序的企业模式下和个人微信小程序在开发过程中除了部分API之外无太大差别，
但是基础库的版本号不同，所以在企业模式下使用wux，在开发者工具中会提示基础库过低。

希望可以在检测基础库的时候对企业微信模式下的小程序开发做一下检测~~

谢谢作者~

**Comment by skyvow** [comment]
@thlz998 目前检测基础库只针对开发者工具。

**Comment by thlz998** [comment]
> @ thlz998目前检测基础库只针对开发者工具。

是的……但是每次进去都要点一次确定，就有点烦……

**Comment by skyvow** [comment]
@thlz998 那你为什么不更改一下？

**Comment by thlz998** [comment]
> @thlz998 那你为什么不更改一下？

改过了，但是还是希望在官方文件中加入相关校验……

**Comment by skyvow** [comment]
@thlz998 加不了，也没意义，企业微信版本与微信版本对小程序兼容性不同。

**Comment by thlz998** [comment]
> @thlz998 加不了，也没意义，企业微信版本与微信版本对小程序兼容性不同。

https://developers.weixin.qq.com/miniprogram/dev/dev_wxwork/

根据微信官方文档，除了增加了部分企业相关的API(比如调取企业通讯录等)，其余与个人微信小程序并无不同，对于wux来说不存在兼容性问题
