### ISSUE TITLE
keyboard 回调问题

### ISSUE THREAD

**Issue by zhk0603** [wux-weapp/wux-weapp#290]
通常密码输入完毕后，都是异步的发送请求到后台进行校验，callback 通过返回 true/false 去控制是否关闭 数字键盘。所以现在没法通过异步的方式去根据后台接口的状态进行控制

我尝试用 await，但是不工作。还是关闭了

![image](https://user-images.githubusercontent.com/15643960/62748856-bcf6f600-ba8c-11e9-8f7b-a566969ef197.png)

**Comment by skyvow** [comment]
@zhk0603 参考示例 Promise

**Comment by zhk0603** [comment]
@skyvow  感谢回复；
我刚看了示例，但是示例的输错密码一样会关闭键盘，我想实现的是根据后台结果，控制关不关闭键盘
