### ISSUE TITLE
swipeaction组件里有一个input，input点击没有光标不能输入

### ISSUE THREAD

**Issue by ShenAlfred** [wux-weapp/wux-weapp#293]
swipeaction组件里使用input，input点击没有光标不能输入

**Comment by ShenAlfred** [comment]
![image](https://user-images.githubusercontent.com/3701134/62930864-d7fc9980-bdef-11e9-8f0a-f5a8eb60a698.png)

**Comment by skyvow** [comment]
@ShenAlfred 未复现

**Comment by skyvow** [comment]
@ShenAlfred 请给出示例
