### ISSUE TITLE
cell真机样式问题

### ISSUE THREAD

**Issue by BullG** [wux-weapp/wux-weapp#297]
`<wux-cell-group >
  <wux-cell title="商户信息维护" isLink url="/pages/my_merInfo/merInfo" openType="navigateTo"></wux-cell>
  <wux-cell title="账户中心" isLink url="/pages/my_accountCenter/accountCenter" openType="navigateTo"></wux-cell>
  <wux-cell title="设置" isLink url="/pages/my_set/set" openType="navigateTo"></wux-cell>
</wux-cell-group>
`

工具上正常
![image](https://user-images.githubusercontent.com/32183716/63311260-16ceaa00-c330-11e9-8d19-2fec31739842.png)

实机上：
![image](https://user-images.githubusercontent.com/32183716/63311275-264df300-c330-11e9-9d34-c4a77baea6aa.png)

**Comment by skyvow** [comment]
@BullG 啥机

**Comment by BullG** [comment]
> @BullG 啥机

1加5T

**Comment by skyvow** [comment]
@BullG 没有这个手机。。。
