### ISSUE TITLE
select 

### ISSUE THREAD

**Issue by grg666** [wux-weapp/wux-weapp#299]
点击选中不了选项 index 始终为-1

**Comment by grg666** [comment]
“1” 与 1  类型导致index 获取不到

**Comment by skyvow** [comment]
@grg666 Select 内部使用 Radio & Checkbox 组件，其 value 必须为 string

**Comment by grg666** [comment]
看了你的代码 是这样写的 既然不是bug话 关闭就好啦

发自我的 iPhone7
