### ISSUE TITLE
请问如何让SwipeAction组件 的点击事件带上参数

### ISSUE THREAD

**Issue by Descartescknn** [wux-weapp/wux-weapp#302]
我的期望：
1.我在一个列表（wx:for）中使用了SwipeAction组件
2.为SwipeAction的侧滑按钮设置了点击事件
3.我想要点击侧滑按钮后获取item的参数

我面对的现象：
1.符合我的期望
2.符合我的期望
3.我在demo中找不到为点击按钮设置参数的示例，在文档中也没有找到。
4.在onClick事件中只能获取所点击的按钮相对于整个侧滑菜单的index，value中倒是可以获取到在
data的right中配置的自定义参数，但是我不太清楚如何修改这个参数。

我希望您能做一下说明，谢谢。

**Comment by skyvow** [comment]
left 或 right 中加入你需要的参数呗，如` [{ text: 'Delete', id: xxx }]`

**Comment by Descartescknn** [comment]
谢谢你的回信，我达成了能实现列表分条目删除的效果，但是我觉得这个编码方式有点奇怪。。


我的思路是这样的：
1.往原始的，需要作为item信息的的集合的元素里添加一个right对象，right对象里的一个自定义参数设置为这个集合的index
2.在xml渲染的时候，从item里取right


最后做出了这样的东西


js:

html:

log:

模拟器展示:

------------------ 原始邮件 ------------------
发件人: "skyvow"<notifications@github.com>;
发送时间: 2019年8月26日(星期一) 晚上7:22
收件人: "wux-weapp/wux-weapp"<wux-weapp@noreply.github.com>;
抄送: "$mile's德"<404699221@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wux-weapp/wux-weapp] 请问如何让SwipeAction组件 的点击事件带上参数 (#302)




left 或 right 中加入你需要的参数呗，如 [{ text: 'Delete', id: xxx }]
