### ISSUE TITLE
怎么解决 ios 低版本下提示Object.getOwnPropertyDescriptors 报错的问题

### ISSUE THREAD

**Issue by dulaoshi** [wux-weapp/wux-weapp#306]
ios 低版本下提示Object.getOwnPropertyDescriptors 报错

**Comment by CongjiZhu** [comment]
有解决方法吗？原来低版本的项目除了重新下载，该如何升级？

**Comment by skyvow** [comment]
@CongjiZhu 
切换到对应的低版本拉取到本地
修改 .babelrc 文件为 `{
    "presets": ["@babel/preset-env"],
    "plugins": ["@babel/plugin-proposal-object-rest-spread"]
}`
修改 package.json 文件下 `"devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/plugin-proposal-object-rest-spread": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/register": "^7.5.5",
    "cross-env": "1.0.8",
    "del": "^5.0.0",
    "gulp": "^4.0.2",
    "gulp-babel": "^8.0.0",
    "gulp-clean-css": "^3.10.0",
    "gulp-cssnano": "^2.1.2",
    "gulp-less": "^3.3.2",
    "gulp-postcss": "^7.0.0",
    "gulp-rename": "^1.2.2",
    "gulp-uglify": "^3.0.2",
    "gulp-util": "^3.0.8",
    "postcss-font-base64": "^1.0.5",
    "through2": "^2.0.3"
  },`
 然后执行 npm install & npm run build 生成 dist 文件

**Comment by CongjiZhu** [comment]
> @CongjiZhu
> 切换到对应的低版本拉取到本地
> 修改 .babelrc 文件为 `{ "presets": ["@babel/preset-env"], "plugins": ["@babel/plugin-proposal-object-rest-spread"] }`
> 修改 package.json 文件下 `"devDependencies": { "@babel/core": "^7.5.5", "@babel/plugin-proposal-object-rest-spread": "^7.5.5", "@babel/preset-env": "^7.5.5", "@babel/register": "^7.5.5", "cross-env": "1.0.8", "del": "^5.0.0", "gulp": "^4.0.2", "gulp-babel": "^8.0.0", "gulp-clean-css": "^3.10.0", "gulp-cssnano": "^2.1.2", "gulp-less": "^3.3.2", "gulp-postcss": "^7.0.0", "gulp-rename": "^1.2.2", "gulp-uglify": "^3.0.2", "gulp-util": "^3.0.8", "postcss-font-base64": "^1.0.5", "through2": "^2.0.3" },`
> 然后执行 npm install & npm run build 生成 dist 文件
配置好了，谢谢解答
