### ISSUE TITLE
date-time-piker，设置一个初始的value，回调会出问题

### ISSUE THREAD

**Issue by JerryZheng7716** [wux-weapp/wux-weapp#310]
比如设置初始的value是["2019","9","1"]，弹出的date-time-view是正常显示的，不修改任何内容，直接点击确定后回调的值有问题。
date: 1567267200000
displayValue: (5) ["2000年", "1月", "1日", "0时", "0分"]
label: "2019-09-01 00:00"
selectedIndex: (5) [0, 0, 0, 0, 0]
selectedValue: (5) ["2000", "0", "1", "0", "0"]
value: (5) ["2000", "0", "1", "0", "0"]
可以看到，除了label以外都是初始值

**Comment by wsyks** [comment]
碰到了相同的问题，请问是解决了吗
