### ISSUE TITLE
wux-fab-button 自定义action图标bug

### ISSUE THREAD

**Issue by MineFurjiko** [wux-weapp/wux-weapp#311]
`<wux-fab-button theme="positive" buttons="{{ buttons }}" bind:click="onClick" action="">`
`　<wux-icon type="ios-refresh" size="28" slot="action"/>`
 ` </wux-fab-button>`

自定义slot插入后，点击时的选择动画没了。。
审查元素看下了，slot并没有插入到 拥有动画view中。。不知道是不是bug

**Comment by skyvow** [comment]
@MineFurjiko 设计如此，非 BUG
