### ISSUE TITLE
上传组件监听不到进度

### ISSUE THREAD

**Issue by LuHugo** [wux-weapp/wux-weapp#314]
上传组件设置了progress为true，也绑定了事件，但上传就是不触发上传事件。
设置uploaded为false时，选择完文件后不触发change事件，选择的图片也没有显示在列表里，这个自定义上传要怎么获得选择的文件？

**Comment by skyvow** [comment]
@LuHugo Show your code.

**Comment by LuHugo** [comment]
@skyvow 自定义上传，选择的本地文件无法在列表显示（选择了文件，还未上传），而且已经把本地文件路径放到fileList，一定要是外部图片才可以显示？
