### ISSUE TITLE
datepicker版本3.8.0有bug，demo小程序上也能复现

### ISSUE THREAD

**Issue by jy05568536** [wux-weapp/wux-weapp#316]
手机：小米6
版本：3.8.0
datepicker默认配置
第一次选弹出来的第一个日期，是2000-02-01
之后再次选中，只调年份，往下滑的时候，弹出层上月份会变为1，但年份选中2014（举例）确定后，日期变为2014-02-01，但用户看到弹出层的日期是2014-01-01
mode 为date、datetime均可以复现

**Comment by ntymm** [comment]
这日期怎么只能选择2000年的，留这么大的坑

**Comment by skyvow** [comment]
@ntymm 请阅读文档

**Comment by ha1ger** [comment]
同样复现了这个BUG，请问下最近会修复吗

**Comment by ha1ger** [comment]
@ntymm 同样复现了这个BUG，请问下最近会修复吗

**Comment by ha1ger** [comment]
@ntymm 你好，date-picker组件这个bug依旧存在，316是只修复了date-picker-view这个组件吗
