### ISSUE TITLE
如何关闭文档网站里的机器猫？

### ISSUE THREAD

**Issue by uiiang** [wux-weapp/wux-weapp#323]
如何关闭文档网站里的机器猫？看着太闹心了

**Comment by skyvow** [comment]
@uiiang 胖虎别哭

**Comment by uiiang** [comment]
跟胖虎没关系，主要是看文档的时候页面是静止不动的，可是旁边却有一个忽上忽下的东西一直在晃，眼睛很难受，就好像右下角总是弹出花里胡哨的广告一样，看着很乱，如果实在不想去掉的话，别做动画也行，让他呆着别动也会好一些
