### ISSUE TITLE
wux-circle真机调试排版错乱

### ISSUE THREAD

**Issue by siaoQ** [wux-weapp/wux-weapp#329]
在开发者工具中，显示正常，如下图：
![image](https://user-images.githubusercontent.com/53051766/67164186-535b6800-f3aa-11e9-8e79-64be7a75f3cd.png)

真机调试时，排版错乱，如下图：

<img width="119" alt="a" src="https://user-images.githubusercontent.com/53051766/67164179-37f05d00-f3aa-11e9-82d6-767ed81651cd.png">

**Comment by skyvow** [comment]
@siaoQ 你写的样式兼容问题吧？
