### ISSUE TITLE
index索引选择器的示例代码有问题

### ISSUE THREAD

**Issue by freechen** [wux-weapp/wux-weapp#335]
`<wux-index height="100%" bind:change="onChange">
    <wux-index-item wx:for="{{ alphabet }}" wx:key="" name="{{ item.initial }}">
        <view class="demo-item" wx:for="{{ item.cells }}" wx:for-item="cell" wx:key="">{{ cell }}</view>
    </wux-index-item>
</wux-index>`

height=“100%”，点击右侧的字母和拖动都不行，改为100vh可以了。请看下是否有这个问题。

**Comment by skyvow** [comment]
@freechen 需自行设置 page{height: 100%;}
