### ISSUE TITLE
tabs 动态加载数据时，current无效，是不是数据迟于界面的初次渲染，指定选中项就无效了？

### ISSUE THREAD

**Issue by zouxianbincc** [wux-weapp/wux-weapp#340]
比如， tabs  的数据，是从网络获取的，当获取回来数据后，指定选中某条，current。但是，此时current是无效的，永远默认是第一条

**Comment by zouxianbincc** [comment]
这场景很容易模拟，开个定时器，几秒后，this.setData() 数据，就可以看到现象了

**Comment by skyvow** [comment]
@zouxianbincc 可以在设置 tabs 数据时，同时设置指定选中某条 current

**Comment by zouxianbincc** [comment]
@skyvow 已经解决了。还有一个新问题，如果让tabs固定在屏上方，不与上下滑动而滚动？
