### ISSUE TITLE
wux-popup-select 组件单选时不显示勾选图标

### ISSUE THREAD

**Issue by jonahfang** [wux-weapp/wux-weapp#345]
两个Taro项目，一个项目能正常显示；另外一个项目就是不能显示。这个项目一开始不能显示，后来我刷新了项目中的所有css文件，又显示了。后来不知道什么原因又不显示了。现在只能暂时放弃使用此组件。

**Comment by TheCityOfSky** [comment]
坑死了，居然没人维护

**Comment by skyvow** [comment]
@TheCityOfSky 能否提供组件版本、BUG复现步骤及相关demo？

**Comment by FreshmanChina** [comment]
我也遇到这个问题,请问怎么解决

**Comment by skyvow** [comment]
@FreshmanChina 能否提供组件版本、BUG复现步骤及相关demo？

**Comment by FreshmanChina** [comment]
只要option的value是数值形式,就会不显示勾选

**Comment by skyvow** [comment]
@FreshmanChina 因为微信小程序原生 checkbox 的 value 仅支持 string，所以这里 option 的 value 也必须是 string。

**Comment by FreshmanChina** [comment]
收到,谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月16日(星期一) 晚上7:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wux-weapp/wux-weapp] wux-popup-select 组件单选时不显示勾选图标 (#345)





 
@FreshmanChina 因为微信小程序原生 checkbox 的 value 仅支持 string，所以这里 option 的 value 也必须是 string。
