### ISSUE TITLE
rater评分组件无法改变星星数量

### ISSUE THREAD

**Issue by royhuang813** [wux-weapp/wux-weapp#346]
```
<wux-rater class="star"  disabled="true" fontSize="14" default-value="{{stat}}" activeColor="#FF8200" />
<text class="star-point">({{stat}}分)</text>
```
场景：进入详情页面，在`onLoad`中监听前一个页面传过来的`start`值，然后`setData()`。

在上述代码`<text>`标签中的值是正确的，但是星星展示的数量一直是`data:{}`中提前申明好的值（如果不提前声明，便是0。

我在组件的js中`console.log`了一下，组件js获取的`inputvalue`值是在页面`onLoad`之前，猜测是因此造成的无法更新。

**Comment by skyvow** [comment]
@royhuang813 使用[受控组件](https://wux-weapp.github.io/wux-weapp-docs/#/controlled)
