### ISSUE TITLE
ActionSheet 中的destructiveValue还是有用的啊

### ISSUE THREAD

**Issue by debj031634** [wux-weapp/wux-weapp#349]
之前的版本中destructiveValue这一个特性还是很有用的，用来做了一些其他传值，结果最近升级这个版本取消了，导致功能出现异常，找了好久才发现，其实代码不多，建议恢复这个特性啊。

**Comment by skyvow** [comment]
@debj031634 destructiveValue？是啥？我没明白。

**Comment by debj031634** [comment]
在原来的版本中，上拉菜单中的删除按钮是可以赋值的，现在这个版本不行了，之前使用这个传值来做数据传值，在这个版本没有了，导致小程序有个功能bug了，今天检查了好久发现是actionsheet：
`<button class="{{ classes.destructive }}" wx:if="{{ destructiveText }}" catchtap="destructiveButtonClicked"  data-value="{{destructiveValue}}">{{ destructiveText }}</button>`
中的data-value没有了

**Comment by skyvow** [comment]
@debj031634 我翻了以前的版本没有加 `destructiveValue ` 的功能。不知道是不是你有改过组件呢？

**Comment by debj031634** [comment]
不应该啊  我还有之前的版本啊。。难道我不是从这里拉下来的版本啊？不过挺好用的。
actionsheet->index.wxml  :
`<button class="{{ classes.destructive }}" wx:if="{{ destructiveText }}" catchtap="destructiveButtonClicked"  data-value="{{destructiveValue}}">{{ destructiveText }}</button>`

actionsheet->index.js:
`/**
         * 删除按钮点击事件
         */
        destructiveButtonClicked(e) {
          const { value } = e.currentTarget.dataset.value
          console.log(e)
            if (this.fns.destructiveButtonClicked(value) === true) {
                this.removeSheet()
            }
        },`

然后就这样：
$wuxActionSheet().showSheet({
            titleText: '自定义操作',
            buttons: [{
                    text: 'Go Dialog'
                },
                {
                    text: 'Go Toast'
                },
            ],
            buttonClicked(index, item) {
              console.log(index,item)
                index === 0 && wx.navigateTo({
                    url: '/pages/dialog/index'
                })

                index === 1 && wx.navigateTo({
                    url: '/pages/toast/index'
                })

                return true
            },
            cancelText: '取消',
            cancel() {},
            destructiveText: '删除',
            destructiveValue: "ceshishishi",
            destructiveButtonClicked(e) {console.log(e)},
        })

难道我之前的版本是谁魔改的？
