### ISSUE TITLE
date-picker组件在MPVUE中选择默认的最小值会报错

### ISSUE THREAD

**Issue by ha1ger** [wux-weapp/wux-weapp#351]
![image](https://user-images.githubusercontent.com/40896893/70882912-40f95580-200c-11ea-959a-1ebc82a9f77f.png)
![image](https://user-images.githubusercontent.com/40896893/70882931-4e164480-200c-11ea-89ed-057db52eed3b.png)

选择01分就不会报错，只有选中设置的最小值2019-01-01 00:00:00才会

**Comment by FayeFayeFaye** [comment]
我在mpvue里使用这个组件  出不来是什么问题啊？
