### ISSUE TITLE
Upload组件怎么限制上传文件的大小

### ISSUE THREAD

**Issue by qiugu** [wux-weapp/wux-weapp#353]
在before方法里面判断文件大小，但是无法阻止文件的上传，还是继续执行了下面的方法，怎么阻止文件上传呢

**Comment by skyvow** [comment]
@qiugu 暂不支持 “限制上传文件的大小”。

**Comment by qiugu** [comment]
有没有计划以后支持一下啊，上传不支持不好用啊
