### ISSUE TITLE
Upload组件，没有上传完成之前请不要显示预览图，删除的时候，选择取消应该保留住图片

### ISSUE THREAD

**Issue by candyAndBella** [wux-weapp/wux-weapp#354]
Upload组件，
1.没有上传到服务器上完成之前，请不要显示预览图，现在是还没有传到服务器上，就会显示图片。
2.删除的时候，弹出confirm层，选择取消应该保留住图片，现在是不管点击“取消”还是“确认”，都删掉了

**Comment by skyvow** [comment]
@candyAndBella 仔细看文档

**Comment by candyAndBella** [comment]
> @candyAndBella 仔细看文档

https://developers.weixin.qq.com/s/6Bt3zVmp7XdE    复现的代码片段

**Comment by candyAndBella** [comment]
![微信截图_20191227140403](https://user-images.githubusercontent.com/34698384/71503935-41b6a500-28b2-11ea-8f2a-cb04e47616b2.png)
![微信截图_20191227140420](https://user-images.githubusercontent.com/34698384/71503937-4418ff00-28b2-11ea-980f-15e3c0ef3232.png)
![微信截图_20191227140432](https://user-images.githubusercontent.com/34698384/71503940-45e2c280-28b2-11ea-889f-5fd92abae1ed.png)

**Comment by candyAndBella** [comment]
![微信截图_20191227140403](https://user-images.githubusercontent.com/34698384/71503960-5d21b000-28b2-11ea-8516-68d693448e67.png)
![微信截图_20191227140420](https://user-images.githubusercontent.com/34698384/71503964-60b53700-28b2-11ea-896e-339ebec1a08c.png)
![微信截图_20191227140432](https://user-images.githubusercontent.com/34698384/71503965-63179100-28b2-11ea-95f9-65ca70fa7bce.png)

**Comment by candyAndBella** [comment]
> @candyAndBella 仔细看文档

在没有上传到开发者的服务器之前，就显示了预览图
在点击删除的时候，还没有点击确定还是取消，就先删除了预览图
图片的显示和删除，应该已开发者的服务器接口为准。。

**Comment by jonahfang** [comment]
@candyAndBella 需要在controlled模式下，才能避免这个删除问题.

**Comment by candyAndBella** [comment]
> @candyAndBella 需要在controlled模式下，才能避免这个删除问题.

嗯嗯，是的。感谢~
