### ISSUE TITLE
日历组件，选择时间范围的时候，选择完起止时间后，当第三次点击的时候，应该清空之前的所选日期

### ISSUE THREAD

**Issue by candyAndBella** [wux-weapp/wux-weapp#355]
日历组件，选择时间范围的时候，选择完起止时间后，当第三次点击的时候，应该清空之前的所选日期。
假如，我选择了2019-12-01，又选择了2019-12-31.那么时间范围已经完成。
如果我又点击了2019-12-15，那么应该默认之前的12月1号和12月31号都清掉了，12-15是新的起始时间。

**Comment by skyvow** [comment]
@candyAndBella 暂不支持选择范围哦
