### ISSUE TITLE
wux-select、wux-popup等凡是有遮罩层的组件，完全打开前就触发关闭时没有完全取消遮罩层

### ISSUE THREAD

**Issue by GitOfZGT** [wux-weapp/wux-weapp#358]
wux-select、wux-popup等凡是有遮罩层的组件，点击打开，又快速的点击遮罩关闭后，导致整个页面无法再点击（遮罩层没有完全取消），举如下例子：
![image](https://user-images.githubusercontent.com/21262000/72312612-9ab07680-36c3-11ea-8add-cab51026b5de.png)
导致遮罩层 opacity:0 , 还在页面上盖着：
![image](https://user-images.githubusercontent.com/21262000/72312412-01816000-36c3-11ea-97df-ca1fdac6e88c.png)

**Comment by GitOfZGT** [comment]
这个问题很严重，很多用户的低端手机，因为反应慢，触发打开wux-select时，没有及时显示出来，以为没点到，又马上点击了一下，复现这种问题很频繁

**Comment by skyvow** [comment]
可以程序控制防止多次触发
