### ISSUE TITLE
吸顶容器能设置顶部的top值吗？

### ISSUE THREAD

**Issue by mr-chen-king** [wux-weapp/wux-weapp#359]
有时候吸顶容器不需要直接顶到屏幕的最上方，能自定义这个吸顶容器的离屏幕最上方的top值吗？
# eg:
![image.png](https://i.loli.net/2020/01/17/QxgOlsB8tX4wcfS.png)

## 想要实现如图的效果，实际的效果是:one:块会直接吸附在屏幕顶部，而不是吸附在:two:块的底部

**Comment by mr-chen-king** [comment]
### 补充说明:two:块已经固定在屏幕顶部 position:fixed

**Comment by skyvow** [comment]
@mr-chen-king v3.8.8 已支持
