### ISSUE TITLE
Keyboard callback with setData is not able to update on ui 

### ISSUE THREAD

**Issue by giaotuancse** [wux-weapp/wux-weapp#363]
`$wuxKeyBoard().show({
      inputText: "Verification code",
      password: false,
      maxlength : 4,
      disorder: false,
      onClose(value) {
        console.log(`输入的密码是：${value}`)
        this.setData({
               pincode: value,
        })
        console.log(this.data.pincode)
        return true
      },
    })`

pincode value is changed but not able to notify to UI. Im using input text to display pinCode value but ui is not refresh pincode is changed.

**Comment by skyvow** [comment]
`onClose: (value) => { this.setData({ pincode: value }) }`
