### ISSUE TITLE
级联选择器在ios上会触发滚动穿透

### ISSUE THREAD

**Issue by kelly1205** [wux-weapp/wux-weapp#367]
级联选择器在ios上会触发滚动穿透，并且导致下面的滚动失效

**Comment by kelly1205** [comment]
![QQ图片20200317163639](https://user-images.githubusercontent.com/31914579/76837442-8cbad580-686d-11ea-9863-6d3011d0e486.gif)

**Comment by skyvow** [comment]
@kelly1205 目前是这样的
