### ISSUE TITLE
Picker当option的value是数字时，滑动选中后会自动跳到第一个

### ISSUE THREAD

**Issue by ifangka** [wux-weapp/wux-weapp#370]
今天碰到一个很奇怪的问题，用Picker当option的value是数字时，滑动选中后会自动跳到第一个

版本3.8.5

如下选项就会出现问题
`options: [
      {value: 1, label: '北京市',},
      {value: 2, label: '浙江省',},
      {value: 3, label: '广东省',},
],`

如下选项就没有问题了。。
`options: [
      {value: '1', label: '北京市',},
      {value: '2', label: '浙江省',},
      {value: '3', label: '广东省',},
],`

**Comment by skyvow** [comment]
@ifangka 对, value 必须 string
