### ISSUE TITLE
datepicker版本3.8.5 月份选择问题，demo小程序上也能复现

### ISSUE THREAD

**Issue by beardidi** [wux-weapp/wux-weapp#371]
手机：一加7Pro
版本：3.8.5
微信：7.0.12

wxml:
` <wux-date-picker  mode="month" value="{{dateValue}}" visible="{{datePickerVisible}}" controlled bind:confirm="datePicker_OnConfirm" bind:cancel="datePicker_OnCancel">
    </wux-date-picker>`

问题：
在月份选择是，会出现大概率的跳下下一个月。比如滑动选择2月，会跳到3月，无论上滑还是下滑都会出现这种情况。

**Comment by beardidi** [comment]
今天问题已经消失，似乎是因为昨天31日的原因？

**Comment by skyvow** [comment]
@beardidi 对，二月没31号超过的会累加到三月，参考其他的日历组件也是这样实现的
