### ISSUE TITLE
js中import报错

### ISSUE THREAD

**Issue by loyilin** [wux-weapp/wux-weapp#372]
使用是ActionSheet时编译报错

![TIM图片20200409164304](https://user-images.githubusercontent.com/20967855/78875938-37936d80-7a81-11ea-9903-2220e6fcb087.png)

**Comment by loyilin** [comment]
import { $wuxActionSheet } from  '../../node_modules/wux-weapp/example/dist/actionsheet/index'

**Comment by skyvow** [comment]
@loyilin 引入路径不对吧，参考 [actionsheet](https://www.wuxui.com/#/actionsheet)
