### ISSUE TITLE
FilterBar筛选栏，点击tabbar时，会取消filterBar之前的选中项。tabbar是vant-weapp的组件

### ISSUE THREAD

**Issue by candyAndBella** [wux-weapp/wux-weapp#381]
![微信截图_20200619171521](https://user-images.githubusercontent.com/34698384/85124010-cd0a6500-b25b-11ea-887d-e9835d8ea866.png)

**Comment by skyvow** [comment]
@candyAndBella 已选中的值可以存下来，切换时赋给默认值？不知道理解的对不对？
