### ISSUE TITLE
筛选-单选 如果value的值和其他值相似，右上角的选项提示会出错！

### ISSUE THREAD

**Issue by iblackly** [wux-weapp/wux-weapp#383]
`
children: [
                    {
                        "label": "1",
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4"
                    },
                    {
                        "label": "5",
                        "value": "5"
                    },
                    {
                        "label": "6",
                        "value": "6"
                    },
                    {
                        "label": "7",
                        "value": "7"
                    },
                    {
                        "label": "8",
                        "value": "8"
                    },
                    {
                        "label": "9",
                        "value": "9"
                    },
                    {
                        "label": "10",
                        "value": "10"
                    },
                    {
                        "label": "11",
                        "value": "11"
                    },
                    {
                        "label": "12",
                        "value": "12"
                    },
                    {
                        "label": "13",
                        "value": "13"
                    },
                    {
                        "label": "14",
                        "value": "14"
                    },
                    {
                        "label": "15",
                        "value": "15"
                    },
                    {
                        "label": "16",
                        "value": "16"
                    },
                    {
                        "label": "17",
                        "value": "17"
                    },
                    {
                        "label": "18",
                        "value": "18"
                    }
            ]
`

https://pics.images.ac.cn/image/5ef1e4a3a60dd.html
https://pics.images.ac.cn/image/5ef1e4a45edad.html
https://pics.images.ac.cn/image/5ef1e4a4c4695.html

**Comment by skyvow** [comment]
@iblackly radio 选择的值是个字符串，源码中使用 `value.includes(v.value)` 判断导致 `其他相似值（如选18,则1.8.18都被选中）`。组件 `filterbar/index.js` 内 `onPopupSelectChange` 函数下 `const { value } = e.detail` 改为 `const value = Array.isArray(e.detail.value) ? e.detail.value : [e.detail.value]`即可。后续也会发新版本修复。

**Comment by iblackly** [comment]
> @iblackly无线电选择的值是个字符串，中源码使用`value.includes(v.value)`判断导致`其他相似值（如选18,则1.8.18都被选中）`。组件`filterbar/index.js`内`onPopupSelectChange`函数下`const { value } = e.detail`对划线`const value = Array.isArray(e.detail.value) ? e.detail.value : [e.detail.value]`即可。后续也会发新版本修复。

谢谢大佬，感谢
