### ISSUE TITLE
wux-upload 参数问题

### ISSUE THREAD

**Issue by a5601564** [wux-weapp/wux-weapp#384]
<wux-upload listType="picture-card" defaultFileList="{{ fileList }}" max="4" url="http://127.0.0.1:8012/upload/file" bind:change="onChange" bind:success="onSuccess" bind:fail="onFail" bind:complete="onComplete" bind:preview="onPreview" bind:remove="onRemove" method="POST" 
        header="{'Content-Type': 'form-data'}"
        formData="{'manageCode':1111,'name':'2222'}">
            <text>Upload</text>
        </wux-upload>

试了很多个方式，都没法将参数传入。

后台接受不到

**Comment by skyvow** [comment]
@a5601564 应该是后端处理问题，[参考一下](https://developers.weixin.qq.com/miniprogram/dev/api/network/upload/wx.uploadFile.html)

**Comment by a5601564** [comment]
首先，打算在这个组件里面能够携带多余的信息。如果可以不就好了？
所以这个功能应该加上去，望珍重。

> @a5601564 应该是后端处理问题，[参考一下](https://developers.weixin.qq.com/miniprogram/dev/api/network/upload/wx.uploadFile.html)

**Comment by skyvow** [comment]
@a5601564 不明白

**Comment by a5601564** [comment]
> @a5601564 不明白

其实，就是 wux-upload 组件没法携带参数的问题，虽然，有替代方案。就是希望能让该组件能增加携带参数功能。
当然，这只是个人的愿景而已。

**Comment by zhangjh** [comment]
意思就是upload组件的formData参数设置了不生效
