### ISSUE TITLE
用wux-tab 切换两个swipe-action 第二个就不能左划出按钮了

### ISSUE THREAD

**Issue by isamu12** [wux-weapp/wux-weapp#388]
<view class="page__bd">
	<wux-tabs current="{{ activeKey }}" controlled bind:change="onChange" theme="positive">
		<wux-tab key="0" title="班级"></wux-tab>
		<wux-tab key="1" title="学员"></wux-tab>
	</wux-tabs>
	
	<view class="content" hidden="{{ activeKey !== '0' }}">
		<wux-swipe-action-group visible="{{ activeKey === '0' }}">
			<wux-swipe-action autoClose right="{{ listRight }}">
				<view class="list-item solid-bottom">班级名称</view>
				<view class="flex">
					<text class="padding cuIcon-friend lg text-gray justify-center">10</text>
					<text class="padding cuIcon-we lg text-gray justify-center">10</text>
				</view>

			</wux-swipe-action>
		</wux-swipe-action-group>
	</view>
	
	<view class="content" hidden="{{ activeKey !== '1' }}">
		<wux-swipe-action-group hidden="{{ activeKey !== '1' }}" >
			<wux-swipe-action autoClose right="{{ OwnerstudentRight }}" >
				<view class="list-item solid-bottom">学员名称</view>
				<view class="flex">
					<text class="padding cuIcon-friend lg text-gray justify-center">10</text>
					<text class="padding cuIcon-we lg text-gray justify-center">10</text>
				</view>
			</wux-swipe-action>
		</wux-swipe-action-group>
	</view>
</view>

**Comment by skyvow** [comment]
@isamu12 可以给一个完整的例子嘛，方便测试
