### ISSUE TITLE
circle组件，第一次加载数据时，圆圈中的内容不更新，开发者工具中显示正常，真机上有问题

### ISSUE THREAD

**Issue by rbj0820** [wux-weapp/wux-weapp#390]
`<wux-circle size="100" percent="{{order.lightPercent}}" color="#32d3eb">{{order.lightPercent}}%</wux-circle>`

  在onLoad钩子函数中获取数据：
   var request = http.weightWarningSummaryQuery(params);
    request.then(res => {
      if (res.data.code == '10000') {
        that.setData({
          order: res.data.data
        })
      } else {
        common.showErrorMessage(res.data.msg);
      }
 
 圆环进度加载正常，但中间的数据显示不出来，后来发现手机屏幕锁屏后，再解锁数据又显示出来，请问该如果解决？

**Comment by skyvow** [comment]
我本地测试没问题。能否提供组件版本、BUG复现步骤及相关demo？
