### ISSUE TITLE
FilterBar 新版本filter中的children若有radio类型，会造成无法选中

### ISSUE THREAD

**Issue by tuhe32** [wux-weapp/wux-weapp#391]
只存在于新版本3.8.6
### WuxUI 版本
3.8.6
### 复现步骤
![image](https://user-images.githubusercontent.com/18496264/89980879-59a63200-dca5-11ea-85c6-5e6523220f18.png)
在新版本中，若fitler类型的children中有radio类型，radio类型即使选中了，点确定，无法在onChange中获取选中项

### 实际的结果是什么？

原因可能是：
>const { value } = e.detail  // radio类型返回是字符串：如 "2"   
> const valueNew = Array.isArray(e.detail.value) ? e.detail.value : [e.detail.value] // 返回数组：如["2"]`

![image](https://user-images.githubusercontent.com/18496264/89981171-02549180-dca6-11ea-82c3-1c6005091b82.png)

**Comment by skyvow** [comment]
@tuhe32 最新版修复了
