### ISSUE TITLE
rater组件按压效果问题

### ISSUE THREAD

**Issue by PingmengWocha** [wux-weapp/wux-weapp#395]
### 小程序基础库版本2.12.2
在禁用rater的点击（disable属性设为false）后任然会有有按压效果

**Comment by skyvow** [comment]
能否提供组件版本、BUG复现步骤及相关demo？

**Comment by PingmengWocha** [comment]
组件版本3.8.7 小程序版本2.12.2，https://developers.weixin.qq.com/s/CRcWOdmD7Ukq

**Comment by PingmengWocha** [comment]
在禁用点击后在点击星星任然会有按压效果

**Comment by skyvow** [comment]
@PingmengWocha 真机没有按压效果，以真机为准
