### ISSUE TITLE
单独使用组件没样式

### ISSUE THREAD

**Issue by rangqian123** [wux-weapp/wux-weapp#396]
你好，请使用下面的模板创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

### WuxUI 版本
wux-weapp@3.8.7
### 小程序基础库版本
2.12.2

### 复现步骤
我直接复制了fab-button，helpers这两个文件夹，
然后再页面里直接使用"wux-fab-button": "../../dist/fab-button/index"
图上面的catchtap="onToggle"，这个view上面没有样式，页面里没报错，这个组件可以点击，只是没有样式

![F93E88D4-C7B8-4993-AA26-6E96B1F19E0A](https://user-images.githubusercontent.com/5977308/92426461-912ccf00-f1bc-11ea-9c40-a251d3a008e0.png)

，我用其他的没用，Swicth试了也没有样式

**Comment by skyvow** [comment]
@rangqian123 检查小程序基础库是否 2.6.6 以上版本 [faq](https://www.wuxui.com/#/faq)

**Comment by rangqian123** [comment]
小程序基础库是2.12.2

**Comment by rangqian123** [comment]
![55DF8AD3-B5F4-4a55-B2DD-0CB838B1EC96](https://user-images.githubusercontent.com/5977308/92451049-cd792300-f1ee-11ea-9712-cbc0ec3da26a.png)
我用原来的版本可以了，这个版本不管单独调什么都没样式
