### ISSUE TITLE
Card 是否可以增加hover-class

### ISSUE THREAD

**Issue by xiaoyaojian** [wux-weapp/wux-weapp#397]
Card 是否可以增加hover-class

**Comment by skyvow** [comment]
@xiaoyaojian 期望实现哪些功能呢？

**Comment by xiaoyaojian** [comment]
我这里用Card展示一个设备的简略信息，按下设备Card时，弹出对设备的操作actionsheet，希望在按下时有按压效果

**Comment by skyvow** [comment]
@xiaoyaojian v3.8.8 已支持
