### ISSUE TITLE
tabs设置scroll后，如果点击到屏幕边缘的标签，tab无法跟随滚动

### ISSUE THREAD

**Issue by qinzhou** [wux-weapp/wux-weapp#400]
- [ ] 我已经搜索过相关 [issues](https://github.com/wux-weapp/wux-weapp/issues) ，确定这个问题没有人提过。

### 你期望的 API 是怎样的？
解决了当前屏幕外的菜单能被用户发现。

### 请确保将 issue 发往相关的仓库。
可以配置一个参数，让开发者选择是否开启标签自动跟随点击而改变位置

**Comment by skyvow** [comment]
@qinzhou Fixed
