### ISSUE TITLE
请问WUX有对应的设计资源吗？比如：Sketch组件

### ISSUE THREAD

**Issue by David-Gan** [wux-weapp/wux-weapp#401]
- [x] 我已经搜索过相关 [issues](https://github.com/wux-weapp/wux-weapp/issues) ，确定这个问题没有人提过。

### 你期望的 API 是怎样的？
方便设计师按照WUX的组件来设计应用

### 请确保将 issue 发往相关的仓库。
期望像Ant Design一样，提供Sketch模板组件

**Comment by skyvow** [comment]
@David-Gan 暂无。。。
