### ISSUE TITLE
Dialog-buttons color issue 对话框按钮颜色问题

### ISSUE THREAD

**Issue by restkhz** [wux-weapp/wux-weapp#402]
- [x] 我已经搜索过相关 [issues](https://github.com/wux-weapp/wux-weapp/issues) ，确定这个问题没有人提过。

### 重现链接
无

### 重现步骤
In fact this is not a complicated problem.

其实这是一个很简单的问题,不过我还是按着流程写了

```javascript
    $wuxDialog().prompt({
      resetOnClose: true,
      title: 'meow',
      content: 'meowmeow',
      fieldtype: 'number',
      defaultText: '',
      placeholder: '1-9999',
      maxlength: 4,
      confirmType: 'calm',     /* here */
      onConfirm(e, response) {
        console.log(response)
      },
    })
```

### 期望的结果是什么？
I just want a blue button instead of always green.

俺只是想要个蓝色的确认按钮 =_= 

### 实际的结果是什么？
No matter how you change 'confirmType', except gray when the confirmType is default, otherwise it's always green.

无论你咋改, 除了default会变灰,永远都是绿色.confirmType形同虚设.

| 环境 | 版本 |
|---|---|
| Wux | v3.8.7 |
| 微信小程序基础库 | 2.14.1 |
| 系统 | 7 |

---
其实这是一个很容易解决的问题.

首先文档中写明了"options.confirmType可以确定按钮的类型", 我希望我没有误解.

可以看一下如下的less

https://github.com/wux-weapp/wux-weapp/blob/master/src/dialog/index.less

在Line 10 定义了默认颜色后除了default和primary(还是默认颜色)以外没有别的颜色.

看了Js和模板写的应该都没有问题,对默认颜色也有处理.

所以其实只需要在Less之中补一些颜色就可以,比如补充深蓝色positive:

```javascript
       /*Add code like this one in the src/dialog/index.less*/
        &--positive {
            color: @positive !important;
        }
```
我做的项目主色调是蓝色还好, 但是不排除某些哥们用的红色作为主要色调,那么有句话叫"红配绿_____."
已经定义好的颜色用一下这并不难,对吧? OuO

最后感谢Wux UI.

**Comment by skyvow** [comment]
@restkhz Good issue. 首先如果项目中主色调是 `深蓝色 positive`，可以通过设置 [样式变量](https://www.wuxui.com/#/customize-theme) 统一修改掉 `@balanced` 对应的颜色，这种方法比较粗暴，所有涉及到的 `@balanced` 都会被修改。最后你提及的： “已经定义好的颜色用一下”，后续版本会尽快加入。

**Comment by restkhz** [comment]
> @restkhz Good issue. 首先如果项目中主色调是 `深蓝色 positive`，可以通过设置 [样式变量](https://www.wuxui.com/#/customize-theme) 统一修改掉 `@balanced` 对应的颜色，这种方法比较粗暴，所有涉及到的 `@balanced` 都会被修改。最后你提及的： “已经定义好的颜色用一下”，后续版本会尽快加入。

的确我应该通过样式变量确定主色调更好一些,没理由到处都用positive和calm...谢谢了

**Comment by skyvow** [comment]
@restkhz v3.8.8 已支持
