### ISSUE TITLE
使用icon图标的时候，总是无法很好的和边上的文字对齐。

### ISSUE THREAD

**Issue by laker55555** [wux-weapp/wux-weapp#414]
- [x] 我已经搜索过相关 [issues](https://github.com/wux-weapp/wux-weapp/issues) ，确定这个问题没有人提过。

### 重现链接
无

### 重现步骤
```
<view class="result-title">
      <view>{{titleshow}}</view>
      <view class="iconouter" wx:if="{{titleArr.length>1}}" bindtap="moretext">
        <wux-icon type="grid-outline" size="18" wux-class="wuxicon" />
      </view>
 </view>
```

### 期望的结果是什么？
文字图标按基准线对齐

### 实际的结果是什么？
图标偏下

| 环境 | 版本 |
|---|---|
| Wux | v3.8.9 |
| 微信小程序基础库 | 2.29.1 |
| 系统 | windows |

**Comment by skyvow** [comment]
`. iconouter { font-size: 0; }`
