### ISSUE TITLE
Error: miniprogram_npm/wux-weapp/cascader-view/index.json: ["usingComponents"]["wux-radio-group"]: "../../dist/radio-group/index" not found

### ISSUE THREAD

**Issue by firebirdluo** [wux-weapp/wux-weapp#418]
- [ ] 我已经搜索过相关 [issues](https://github.com/wux-weapp/wux-weapp/issues) ，确定这个问题没有人提过。

### 重现链接
无

### 重现步骤
使用miniprogram-ci upload时报错../../dist/radio-group/index" not found

### 期望的结果是什么？
这前是正常的现在不行了

### 实际的结果是什么？
Error: miniprogram_npm/wux-weapp/cascader-view/index.json: ["usingComponents"]["wux-radio-group"]: "../../dist/radio-group/index" not found

| 环境 | 版本 |
|---|---|
| Wux | v3.10.0 |
| 微信小程序基础库 | node v16.19.1   npm 9和8都有问题 |
| 系统 | debian |

**Comment by ZhouT1024** [comment]
![image](https://github.com/wux-weapp/wux-weapp/assets/58963734/bd0e845e-87d0-4493-a188-6918e4227961)

cascader-view组件引用radio组件时用的路径有错
