### ISSUE TITLE
cascader-view组件编译错误

### ISSUE THREAD

**Issue by Kobe972** [wux-weapp/wux-weapp#424]
- [ ] 我已经搜索过相关 [issues](https://github.com/wux-weapp/wux-weapp/issues) ，确定这个问题没有人提过。

### 重现链接
无

### 重现步骤
npm导入项目，组件里引用/miniprogram_npm/wux-weapp/cascader-view/index

### 期望的结果是什么？
不报错

### 实际的结果是什么？
[ WXML 文件编译错误] 
./miniprogram_npm/wux-weapp/cascader-view/index.wxml:42:1:../helpers/wxs/common.wxs not found from ./miniprogram_npm/wux-weapp/cascader-view/index.wxml(env: Windows,mp,1.06.2402030; lib: 3.3.4)

| 环境 | 版本 |
|---|---|
| Wux | v3.10.1 |
| 微信小程序基础库 | 3.3.4 |
| 系统 | Android |

**Comment by skyvow** [comment]
@Kobe972 已修复，更新一下
