### ISSUE TITLE
https://api.github.com 不在以下 request 合法域名列表中

### ISSUE THREAD

**Issue by apifamily** [wux-weapp/wux-weapp#70]
pages/filterbar/index.js 里面请求了接口`https://api.github.com/search/repositories`，但是github.com是没有进行ICP备案的，请问如何解决呢？十分感谢！

**Comment by LY-Eric** [comment]
你在小程序开发设置里把这个域名加进去。




from Allen
在2018年06月26日 16:01，狗十三 写道：

pages/filterbar/index.js 里面请求了接口https://api.github.com/search/repositories，但是github.com是没有进行ICP备案的，请问如何解决呢？十分感谢！

**Comment by skyvow** [comment]
@apifamily 勾选不校验合法域名
