### ISSUE TITLE
actionsheet中联动另一个actionsheet怎么处理？

### ISSUE THREAD

**Issue by pepperdog999** [wux-weapp/wux-weapp#71]
如题，在第一个actionsheet中点击某按钮，如果要触发另一个actionsheet该如何处理？
如果第一个actionsheet的点击事件中return true，会导致第二个actionsheet没法显示。

**Comment by skyvow** [comment]
@pepperdog999 第二个调用一个新的组件如 $wuxActionSheet('#wux-actionsheet2')
