### ISSUE TITLE
有关 Gallery 缩放和 Dialog 高亮的小问题

### ISSUE THREAD

**Issue by treefung** [wux-weapp/wux-weapp#76]
感谢作者，有两个小问题询问

1. Gallery 不能像原生那样手指拉伸缩放？文档里没有发现 option

2. Dialog 按钮 点击时没有高亮反馈？类似于原生这样的点击加深背景色

![image](https://user-images.githubusercontent.com/39109757/43688556-b2118796-991d-11e8-9779-604d75ee29c5.png)

**Comment by skyvow** [comment]
@treefung Gallery 暂不支持缩放功能，Dialog 高亮反馈后续会加入。
