### ISSUE TITLE
关于自定义样式的想法

### ISSUE THREAD

**Issue by yuweizhang1991** [wux-weapp/wux-weapp#77]
现在组件的质量是很不错的了，但是在有些见面对于有的组件样式可能需要修改，当然自己修改源文件可以实现，只是相对麻烦，而且其他地方使用可能就是原来的样式就可以了，我想的是组件能否提供一个自定义样式的参数呢~个人觉得这样会有更多用户

**Comment by skyvow** [comment]
@yuweizhang1991 大部分组件都提供了[外部样式类](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html) wux-class 字段，仅对当前节点生效，如果要求比较复杂，还是建议修改源文件。

**Comment by yuweizhang1991** [comment]
好的，现在开始写demo，刚用这个组件，慢慢研究一下
