### ISSUE TITLE
Dialog 遮罩的问题，多图示范

### ISSUE THREAD

**Issue by treefung** [wux-weapp/wux-weapp#78]
![](https://user-images.githubusercontent.com/39109757/43758826-e2a2554c-9a4f-11e8-8b22-df3636cb8b49.png)

顺序从左到右6张

图1 实机 iPhone 6SP 官方 showMdoal 遮罩正常
图2 实机 iPhone 6SP wxu.Dialog   map 和 textarea placeholder 遮罩不正常
图3 实机 Samsung S9+  wxu.Dialog  map  遮罩不正常
图4 实机 Samsung S9+ 官方 showMdoal 遮罩正常
图5 开发工具 官方 showMdoal 遮罩正常
图6 开发工具 wxu.Dialog 遮罩正常

video无法遮罩 官方已经给出说明，还想询问下作者 开发工具无法调试伪类有什么解决方案吗？

**Comment by treefung** [comment]
![image](https://user-images.githubusercontent.com/39109757/43758826-e2a2554c-9a4f-11e8-8b22-df3636cb8b49.png)

**Comment by treefung** [comment]
查询了一下 textarea video map 层级都是最高的 z-index 无效 只能曲线救国了

**Comment by skyvow** [comment]
嗯，一些原生组件层级最高，建议使用官方 showMdoal 遮罩。调试伪类我也没什么好的方法，记得以前的老版本可以查看。

**Comment by treefung** [comment]
官方 showMdoal 很多实现不了 举个简单的例子现在获取用户权限 都要手动点击 button 我想把模态框的确定 直接 opensetting 但是官方的 只有 view 所以我把 自定义的 view 确定改为 butoon 不知道思路对不对

**Comment by skyvow** [comment]
@treefung 对的

**Comment by treefung** [comment]
@skyvow https://github.com/chemzqm/wept 可以尝试这个调试伪类
