### ISSUE TITLE
spin组件显示问题

### ISSUE THREAD

**Issue by chasel34** [wux-weapp/wux-weapp#86]
#### 问题
spin组件的属性spinning一开始设置为true，在onload的时候修改值为false后组件的蒙层消失，但是dot和tip不消失，设置一定的延时条件后可以正常消失。

#### 图片
![image](https://user-images.githubusercontent.com/23191158/44465931-8c3a6880-a651-11e8-8d88-1d9f17f60428.png)

#### 环境
 - 设备:  pc 微信开发者工具v1.02.1808100
 - 基础库版本: 2.2.3
 - wux-weapp 版本: v 3.0.4

**Comment by skyvow** [comment]
@chasel34 感谢反馈，原因是 animation-group 组件导致的，后续会修复。
