### ISSUE TITLE
[BUG] actionsheet 的位置是有问题的

### ISSUE THREAD

**Issue by shenxiang11** [wux-weapp/wux-weapp#88]
<img width="307" alt="2018-08-24 12 14 13" src="https://user-images.githubusercontent.com/17292115/44564870-e47b8280-a797-11e8-9be8-38e6c825c0b2.png">
<img width="312" alt="2018-08-24 12 13 09" src="https://user-images.githubusercontent.com/17292115/44564767-66b77700-a797-11e8-81de-9e3940eac46f.png">

因为使用场景是列表

**Comment by skyvow** [comment]
@shenxiang11 如何复现，可否给出示例

**Comment by shenxiang11** [comment]
![wechatimg11](https://user-images.githubusercontent.com/17292115/44578476-49e66800-a7c6-11e8-807e-98d2a5eee79e.jpeg)
就是官方例子的代码，就像是网页中fixed定位用了absolute定位

**Comment by skyvow** [comment]
@shenxiang11 嗯，发现了是定位问题，后续有修复
