### ISSUE TITLE
npm怎么使用？

### ISSUE THREAD

**Issue by tflgithub** [wux-weapp/wux-weapp#89]
可以把npm使用写的更具体些么

**Comment by skyvow** [comment]
https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html

**Comment by Gokeyoung** [comment]
项目：git执行  `npm install wux-weapp`

**Comment by Patrick-Jun** [comment]
把这句写在介绍文档如何，果然issue里有人问。
`npm install wux-weapp`
不写清楚我都怀疑是npm install wuxWeapp等
