### ISSUE TITLE
button组件无法提交表单

### ISSUE THREAD

**Issue by bao2314483** [wux-weapp/wux-weapp#98]
button组件设置formType='submit'时,点击无法提交表单

**Comment by skyvow** [comment]
@bao2314483 目前，设置了 form-type 的 button 只会对当前组件中的 form 有效。因而，将 button 封装在自定义组件中，而 from 在自定义组件外，将会使这个 button 的 form-type 失效。

**Comment by bao2314483** [comment]
`<form bindsubmit='formSubmit'>
    <view class='login-input'>
      <i class="chy icon-phone"></i>
      <input name="telno" type='number' placeholder-class="login-input-phcolor" placeholder="请输入手机号码" bindblur='telnochange'></input>
      <view class="login-input-vcodebtn" bindtap="vcode">{{ c2 || '获取验证码' }}</view>
    </view>
    <view class='login-input'>
      <i class="chy icon-code"></i>
      <input name="code" type='number' placeholder-class="login-input-phcolor" placeholder="请输入验证码"></input>
    </view>
    <view class='login-btnview'>
      <wux-button block type="balanced" formType="submit">登录</wux-button>
    </view>
  </form>`

我是设置在表单组件内,但是无法触发表单提交事件
