### ISSUE TITLE
日历组件和echarts图层遮盖

### ISSUE THREAD

**Issue by ZeyZhang** [wux-weapp/wux-weapp#99]
如下图所示，在安卓真机上echart图层与日历组件发生重叠，开发者工具调试显示正常
![image](https://user-images.githubusercontent.com/20785848/45807387-f3e9df00-bcf5-11e8-8132-c217210b4246.png)

**Comment by skyvow** [comment]
@ZeyZhang https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html

**Comment by ZeyZhang** [comment]
@skyvow 可是我使用cover-view包裹在日历组件外部，会提醒如下图的错误。应该如何解决这个问题？
![image](https://user-images.githubusercontent.com/20785848/45855041-d6158c00-bd80-11e8-9f13-2c8f28cd6bf3.png)
